//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibrary.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBLIBRARYEntities1 : DbContext
    {
        public DBLIBRARYEntities1()
            : base("name=DBLIBRARYEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLABOUT> TBLABOUT { get; set; }
        public virtual DbSet<TBLACTION> TBLACTION { get; set; }
        public virtual DbSet<TBLANNOUNCEMENTS> TBLANNOUNCEMENTS { get; set; }
        public virtual DbSet<TBLAUTHOR> TBLAUTHOR { get; set; }
        public virtual DbSet<TBLBANK> TBLBANK { get; set; }
        public virtual DbSet<TBLBOOK> TBLBOOK { get; set; }
        public virtual DbSet<TBLCATEGORY> TBLCATEGORY { get; set; }
        public virtual DbSet<TBLCONTACT> TBLCONTACT { get; set; }
        public virtual DbSet<TBLMEMBERS> TBLMEMBERS { get; set; }
        public virtual DbSet<TBLMESSAGES> TBLMESSAGES { get; set; }
        public virtual DbSet<TBLPENALTY> TBLPENALTY { get; set; }
        public virtual DbSet<TBLSTAFF> TBLSTAFF { get; set; }
    }
}
