//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibrary.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPENALTY
    {
        public int ID { get; set; }
        public Nullable<int> MEMBER { get; set; }
        public Nullable<int> ACTION { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<decimal> MONEY { get; set; }
    
        public virtual TBLACTION TBLACTION { get; set; }
        public virtual TBLMEMBER TBLMEMBER { get; set; }
    }
}
